var studentNames:string[]=["Usman","Zahid","Kashif","Sarfraz","Kamran", "Sami"]
console.log(studentNames)

studentNames.push("hafeez")
console.log(studentNames)
studentNames.push("Yasir")
console.log(studentNames)
studentNames.pop()
console.log(studentNames)
studentNames.pop()
console.log(studentNames)
studentNames.pop()
console.log(studentNames)
studentNames.unshift("Ayyan")
console.log(studentNames)
studentNames.unshift("Khurram")
console.log(studentNames)
studentNames.unshift("Khurram")
console.log(studentNames);
studentNames.unshift("Zaffar")
console.log(studentNames);
studentNames.unshift("Shah Jee")
console.log(studentNames)
studentNames.shift()
console.log(studentNames)
studentNames.shift()
console.log(studentNames)
studentNames.shift()
console.log(studentNames)
studentNames.shift()
console.log(studentNames)